stages:
  - deploy

deploy-internal:
  stage: deploy
  environment:
    name: internal
  only:
    - main
  when: manual
  tags: ['intranet']
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh gitlab-ci@hsensw-geoportal-berlin-mde.intranet.terrestris.de mkdir -p mde/nginx
    - ssh gitlab-ci@hsensw-geoportal-berlin-mde.intranet.terrestris.de mkdir -p mde/postgres
    - scp docker-compose-internal.yaml gitlab-ci@sensw-geoportal-berlin-mde.intranet.terrestris.de:mde/docker-compose.yaml
    - scp nginx/internal-test/default.conf gitlab-ci@sensw-geoportal-berlin-mde.intranet.terrestris.de:mde/nginx/default.conf
    - scp -r mde-postgres/init-data/ gitlab-ci@sensw-geoportal-berlin-mde.intranet.terrestris.de:mde/mde-postgres/
    - ssh gitlab-ci@sensw-geoportal-berlin-mde.intranet.terrestris.de podman compose pull
    - ssh gitlab-ci@sensw-geoportal-berlin-mde.intranet.terrestris.de podman compose up -d
