services:
  mde-nginx:
    container_name: mde-nginx
    hostname: mde-nginx
    image: nginx
    privileged: true
    restart: unless-stopped
    volumes:
      - ./mde-nginx/prod/default.conf:/etc/nginx/conf.d/default.conf:rw,U
      - ./mde-nginx/prod/gdi-con-t-server.selfsign.crt:/etc/nginx/ssl/private/gdi-con-t-server.selfsign.crt:U
      - ./mde-nginx/prod/gdi-con-t-server.key:/etc/nginx/ssl/private/gdi-con-t-server.key:U
    ports:
      - 80:80
      - 443:443
    healthcheck:
      test: ['CMD', 'curl', '-k', '-f', 'https://localhost']
      interval: 5m
      timeout: 3s
      start_period: 30s
    depends_on:
      - mde-gnos
      - mde-backend
      - mde-client
      - mde-keycloak
  mde-postgres:
    container_name: mde-postgres
    hostname: mde-postgres
    image: postgres:17
    privileged: true
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./mde-postgres/postgresql_data:/var/lib/postgresql/data:rw,U
      - ./mde-postgres/init_data:/docker-entrypoint-initdb.d
  mde-keycloak:
    container_name: mde-keycloak
    hostname: mde-keycloak
    image: quay.io/keycloak/keycloak:26.0
    restart: unless-stopped
    depends_on:
      - mde-postgres
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: mde-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOST}
      KC_HOSTNAME_PATH: /auth
      KC_HTTP_RELATIVE_PATH: /auth
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: ["start", "--proxy-headers", "xforwarded", "--http-enabled", "true"]
  mde-backend:
    image: ghcr.io/gdi-be/mde-backend
    container_name: mde-backend
    hostname: mde-backend
    restart: unless-stopped
    depends_on:
      - mde-postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      VARIABLE_FILE: ${VARIABLE_FILE}
    volumes:
      - ./mde-backend/lucene:/lucene
      - ./mde-backend/keystore/cacerts:/opt/java/openjdk/lib/security/cacerts:U
      - ./mde-backend/variables.json:/variables.json:U
      - ./codelists:/data/codelists:U
    privileged: true
  mde-client:
    image: ghcr.io/gdi-be/mde-client:main
    container_name: mde-client
    hostname: mde-client
    restart: unless-stopped
    volumes:
      - .client-env:/app/.env:U
      - ./codelists:/data/codelists:U
    privileged: true
