services:
  mde-nginx:
    container_name: mde-nginx
    hostname: mde-nginx
    image: nginx
    privileged: true
    restart: unless-stopped
    volumes:
      - ./mde-nginx/prod/default.conf:/etc/nginx/conf.d/default.conf:rw,U
      - ./mde-nginx/prod/gdi-mde-p-server.selfsign.crt:/etc/nginx/ssl/private/localhost.crt:U
      - ./mde-nginx/prod/gdi-mde-p-server.key:/etc/nginx/ssl/private/localhost.key:U
    ports:
      - 80:80
      - 443:443
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost"]
      interval: 5m
      timeout: 3s
      start_period: 30s
    depends_on:
      - mde-gnos
      - mde-backend
      - mde-client
      - mde-keycloak
  mde-keycloak:
    container_name: mde-keycloak
    hostname: mde-keycloak
    image: quay.io/keycloak/keycloak:26.0
    restart: unless-stopped
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: ${POSTGRES_HOST}
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOST}
      KC_HOSTNAME_PATH: /auth
      KC_HTTP_RELATIVE_PATH: /auth
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command:
      ["start", "--proxy-headers", "xforwarded", "--http-enabled", "true"]
  mde-backend:
    image: ghcr.io/gdi-be/mde-backend:3.9.3
    container_name: mde-backend
    hostname: mde-backend
    restart: unless-stopped
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      VARIABLE_FILE: ${VARIABLE_FILE}
      CSW_SERVER: ${CSW_SERVER}
      CSW_USER: ${CSW_USER}
      CSW_PASSWORD: ${CSW_PASSWORD}
      CODELISTS_DIR: ${CODELISTS_DIR}
      JAVA_TOOL_OPTIONS: "-Dlog4j2.configurationFile=/config/log4j2.properties"
    volumes:
      - ./mde-backend/lucene:/lucene
      - ./mde-backend/keystore/cacerts:/opt/java/openjdk/lib/security/cacerts:U
      - ./mde-backend/variables.json:/variables.json:U
      - ./mde-backend/log4j2.properties:/config/log4j2.properties
      - ./codelists:/data/codelists:U
    privileged: true
  mde-client:
    image: ghcr.io/gdi-be/mde-client:3.21.0
    container_name: mde-client
    hostname: mde-client
    restart: unless-stopped
    volumes:
      - .client-env:/app/.env:U
      - ./codelists:/data/codelists:U
      - ./mde-backend/variables.json/:/data/variables.json:U
    privileged: true
